### ISSUE TITLE
eslint out of project

### ISSUE THREAD

**Issue by xxn520** [tleunen/eslint-import-resolver-babel-module#66]
My eslint is in a devtool, although `plug.container` and `target` is both `babel-plugin-module-resolver`, but they are from two node_modules, so the `plug.container === target` is still `false`。

now I use 
```
const targetPlugin = require(`${projectRootDir}/node_modules/babel-plugin-module-resolver`).default;
``` 
to fix it.

Is there any other solution for eslint out of project.

**Comment by tleunen** [comment]
Could you explain why you don't have eslint in your project?
I'm not sure to understand.

**Comment by xxn520** [comment]
We have a lot of projects, so we develop a cli tool that contains `eslint` to support all projects. We install this cli tool globally, rather than install eslint in every project.

**Comment by tleunen** [comment]
Does it mean you have 2 different `babel-plugin-module-resolver` installed in your setup?

To be able to fix your issue, instead of an object comparison with the container, we could check the name of the plugin instead. But I don't know if it's an information we have access to.

Instead of changing the `getPlugin` call. Could you try to replace the condition `plug && plug.container === target` by `plug && plug.plugin.key === 'module-resolver'`?

**Comment by tleunen** [comment]
I updated to use the name instead. In latest master (not published yet). Hopefully it will solve your issue.
https://github.com/tleunen/eslint-import-resolver-babel-module/blob/master/src/index.js#L26
